In [6]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np


In [16]:
text="this is a sample input"

chars=sorted(list(set(text)))
chars
    

[' ', 'a', 'e', 'h', 'i', 'l', 'm', 'n', 'p', 's', 't', 'u']

In [17]:
len(text)


22

In [3]:
charidx={u:i for i,u in enumerate(chars)}

In [4]:
charidx

{' ': 0,
 'a': 1,
 'e': 2,
 'h': 3,
 'i': 4,
 'l': 5,
 'm': 6,
 'n': 7,
 'p': 8,
 's': 9,
 't': 10,
 'u': 11}

In [62]:
idxchar = {i: char for i, char in enumerate(chars)}

In [63]:
idxchar

{0: ' ',
 1: 'a',
 2: 'e',
 3: 'h',
 4: 'i',
 5: 'l',
 6: 'm',
 7: 'n',
 8: 'p',
 9: 's',
 10: 't',
 11: 'u'}

In [64]:
##CREATE SEQUENCES AND LABELS FOR THE RNN MODEL
## LETS KEEP THE SEQ LENGTH TO BE 3
seq_length = 3
sequences = []
labels = []

for i in range(len(text) - seq_length):
    seq = text[i:i+seq_length]
    label = text[i+seq_length]
    sequences.append([charidx[char] for char in seq])
    labels.append(charidx[label])

In [65]:
sequences

[[10, 3, 4],
 [3, 4, 9],
 [4, 9, 0],
 [9, 0, 4],
 [0, 4, 9],
 [4, 9, 0],
 [9, 0, 1],
 [0, 1, 0],
 [1, 0, 9],
 [0, 9, 1],
 [9, 1, 6],
 [1, 6, 8],
 [6, 8, 5],
 [8, 5, 2],
 [5, 2, 0],
 [2, 0, 4],
 [0, 4, 7],
 [4, 7, 8],
 [7, 8, 11]]

In [66]:
labels

[9, 0, 4, 9, 0, 1, 0, 9, 1, 6, 8, 5, 2, 0, 4, 7, 8, 11, 10]

In [67]:
X=np.array(sequences)
y=np.array(labels)
X=tf.one_hot(X,len(chars))
y=tf.one_hot(y,len(chars))

In [68]:
X

<tf.Tensor: shape=(19, 3, 12), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [

In [69]:
y

<tf.Tensor: shape=(19, 12), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.

In [70]:
from tensorflow.keras.layers import SimpleRNN
model=Sequential()
model.add(SimpleRNN(100,input_shape=(seq_length,len(chars)),activation='relu'))
model.add(Dense(len(chars),activation='softmax'))

In [71]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [72]:
model.fit(X, y, epochs=100)


Epoch 1/100
1/1 [==============================] - 0s 228ms/step - loss: 2.4616 - accuracy: 0.2105
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 2.4270 - accuracy: 0.2105
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 2.3929 - accuracy: 0.2632
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 2.3597 - accuracy: 0.2632
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 2.3275 - accuracy: 0.3158
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 2.2957 - accuracy: 0.3158
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 2.2642 - accuracy: 0.3684
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 2.2334 - accuracy: 0.3684
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 2.2027 - accuracy: 0.3684
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 2.1720 - accuracy: 0.3684
Epoch 11/100
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 0.1699 - accuracy: 0.9474
Epoch 85/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1671 - accuracy: 0.9474
Epoch 86/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1645 - accuracy: 0.9474
Epoch 87/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1621 - accuracy: 0.9474
Epoch 88/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1597 - accuracy: 0.9474
Epoch 89/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1575 - accuracy: 0.9474
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1554 - accuracy: 0.9474
Epoch 91/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1534 - accuracy: 0.9474
Epoch 92/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1514 - accuracy: 0.9474
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1496 - accuracy: 0.9474
Epoch 94/100
1/1 [===============

In [76]:
start_seq = "this is a"
generated_text = start_seq

for i in range(10):
    x = np.array([[charidx[char] for char in generated_text[-seq_length:]]])
    x_one_hot = tf.one_hot(x, len(chars))
    prediction = model.predict(x_one_hot)
    next_index = np.argmax(prediction[0])
    next_char = idxchar[next_index]
    generated_text += next_char

print("Generated Text:")
print(generated_text)

1/1 [==============================] - 0s 8ms/step
Generated Text:
this is a sample in
